# This is a basic workflow to help you get started with Actions

name: AWS deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 and run
        run: |
          export AWS_KEY = ${{secrets.AWS_SECRET_ACCESS_KEY}}
          echo "$AWS_KEY" >> key.pem
          chmod 400 key.pem
          sudo ssh -i "key.pem" ubuntu@ec2-3-135-18-68.us-east-2.compute.amazonaws.com
      - name: Run commands
        run: |  
          cd Gerbot
          git pull
          cd src/
          cd mkdir api_keys
          touch __init__.py
          touch api_keys
          touch cat.py && echo 'api key = ${{secrets.CAT_KEY}}' >> cat.py
          touch twitter_keys && echo 'api key =${{secrets.TWITTER_API_KEY}}' >> twitter_keys.py
          touch twitter_keys && echo 'api_secret =${{secrets.TWITTER_API_SECRETS}}' >> twitter_keys.py
          touch twitter_keys && echo 'bearer_token =${{secrets.TWITTER_BEARER_TOKEN}}' >> twitter_keys.py
          touch twitter_keys && echo 'access_token =${{secrets.TWITTER_ACCESS_TOKEN}}' >> twitter_keys.py
          touch twitter_keys && echo 'access_token_secret =${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}' >> twitter_keys.py
          cd ../
          python3 main.py

          
          
          
          
          
          
      
