# Deploys a payload to the server to get the latest data
name: Deploy to Gerbot server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.9 
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: Dockerize
        run: |
          docker build ./Dockerfile -t Gerbot
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
        

          

