# Runs tests for code when we get a pull

name: Code test

on:
  pull_request:
    branches: [ master]

jobs:
  code_test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7.9 
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: flake8 Lint
        uses: py-actions/flake8@v1

          
          
        
     
